AWSTemplateFormatVersion: "2010-09-09"
Description: LoadBalancer Template
Parameters:
  ProjectName:
    Type: String
    Default: demo
    Description: Project name
  RecordName:
    Type: String
    Default: "*.demo.example.com"
    Description: Record name

Resources:
  ##############################
  # ALB
  ##############################
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}-alb
      Subnets:
        - { "Fn::ImportValue": !Sub "${ProjectName}-frontend-subnet1" }
        - { "Fn::ImportValue": !Sub "${ProjectName}-frontend-subnet2" }
        - { "Fn::ImportValue": !Sub "${ProjectName}-frontend-subnet3" }
      SecurityGroups:
        - { "Fn::ImportValue": !Sub "${ProjectName}-alb-sg" }
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-alb"
      Scheme: internet-facing
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn:
            { "Fn::ImportValue": !Sub "${ProjectName}-certificate-arn" }
      SslPolicy: "ELBSecurityPolicy-2016-08"
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: "text/plain"
            StatusCode: "404"
            MessageBody: "NotFound"

  R53RecordSetGroup:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneId:
        { "Fn::ImportValue": !Sub "${ProjectName}-hosted-zone-id" }
      RecordSets:
        - Name: !Sub "${RecordName}"
          Type: A
          AliasTarget:
            HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
            DNSName: !GetAtt LoadBalancer.DNSName

Outputs:
  LoadBalancerArn:
    Value: !Ref "LoadBalancer"
    Export:
      Name: !Sub "${ProjectName}-alb-arn"
  LoadBalancerListenerArn:
    Value: !Ref "LoadBalancerListener"
    Export:
      Name: !Sub "${ProjectName}-alb-listener-arn"
