AWSTemplateFormatVersion: "2010-09-09"
Description: ECR Template
Parameters:
  NameTagPrefix:
    Type: String
    Default: demo
    Description: Prefix of Name tags.

Resources:
  ##############################
  # ECR
  ##############################
  AppRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${NameTagPrefix}-app"
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Delete old images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  AppRepository:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AppRepository}"
    Export:
      Name: !Sub "${NameTagPrefix}-app-repository"
