AWSTemplateFormatVersion: "2010-09-09"
Description: ECR Template
Parameters:
  NameTagPrefix:
    Type: String
    Default: demo
    Description: Prefix of Name tags.

Resources:
  ##############################
  # ECR
  ##############################
  AppRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${NameTagPrefix}-app"
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Delete old images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  AppRepository:
    Value:
      !Sub [
        "${Param1}.dkr.ecr.${Param2}.amazonaws.com/${Param3}",
        {
          Param1: !Ref "AWS::AccountId",
          Param2: !Ref "AWS::Region",
          Param3: !Ref "AppRepository",
        },
      ]
    Export:
      Name: !Sub "${NameTagPrefix}-app-repository"
