AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Cluster Template
Parameters:
  NameTagPrefix:
    Type: String
    Default: demo
    Description: Prefix of Name tags.

Resources:
  ##############################
  # IAM Role
  ##############################
  # Fargate（アプリケーション）に付与する権限
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${NameTagPrefix}-ecs-task-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"

  # Fargate の起動に必要な権限
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${NameTagPrefix}-ecs-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"

  ##############################
  # ECS Task Denisition
  ##############################
  ECSTaskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${NameTagPrefix}-template"
      RetentionInDays: 3

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${NameTagPrefix}-template"
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: app
          Image:
            !Sub [
              "${Param1}:init",
              {
                Param1:
                  { "Fn::ImportValue": !Sub "${NameTagPrefix}-app-repository" },
              },
            ]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSTaskLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
          PortMappings:
            - HostPort: 80
              Protocol: tcp
              ContainerPort: 80
          Environment:
            - Name: APP_NAME
              Value: sample

  ##############################
  # ECS Service
  ##############################
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: { "Fn::ImportValue": !Sub "${NameTagPrefix}-ecs-cluster" }
      ServiceName: !Sub ${NameTagPrefix}-service
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref ECSTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - { "Fn::ImportValue": !Sub "${NameTagPrefix}-alb-sg" }
          Subnets:
            - { "Fn::ImportValue": !Sub "${NameTagPrefix}-frontend-subnet1" }
            - { "Fn::ImportValue": !Sub "${NameTagPrefix}-frontend-subnet2" }
            - { "Fn::ImportValue": !Sub "${NameTagPrefix}-frontend-subnet3" }

Outputs:
  ECSService:
    Value: !Ref ECSService
    Export:
      Name: !Sub "${NameTagPrefix}-ecs-service"
