AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Cluster Template
Parameters:
  ProjectName:
    Type: String
    Default: demo
    Description: Project name

Resources:
  ##############################
  # ECS Cluster
  ##############################
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${ProjectName}-cluster"
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Base: 1
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Base: 0
          Weight: 9

Outputs:
  ECSCluster:
    Value: !Ref "ECSCluster"
    Export:
      Name: !Sub "${ProjectName}-ecs-cluster"
